[package]
name = "product-graph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

actix-web = "4.2"
actix-web-lab = "0.19"
actix-cors = "0.6"
juniper = "0.15"
tokio = { version = "1", features = ["macros"] }
env_logger = "0.10.0"
log = "0.4"

reqwest = { version = "0.11", default-features = false, features = [
    "json",
    "rustls-tls",
] }
base64 = "0.21.0"
serde_json = "1.0.94"
serde_derive = "1.0.154"
serde = "1.0.154"
