# fly.toml file generated for ederoyd-product-graph on 2023-03-31T15:54:58+01:00

app = "ederoyd-product-graph"
kill_signal = "SIGINT"
kill_timeout = 5

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
