app = "ederoyd-product-graph"
app_description = "Ederoyd Product Graph"
primary_region = "lhr"

app_version = "0.0.1"
app_license = "MIT"

experimental.private_network = true

kill_signal = "SIGINT"
kill_timeout = 5

[processes]
graph = "/product-graph"

[[services]]
protocol = "tcp"
internal_port = 8080
processes = ["graph"]
auto_stop_machines = true
auto_start_machines = true

[[services.ports]]
port = 80
handlers = ["http"]

[services.concurrency]
type = "requests"
hard_limit = 25
soft_limit = 20
