app = "ederoyd-product-graph"
app_description = "Ederoyd Product Graph"
primary_region = "lhr"

app_version = "0.0.1"
app_license = "MIT"

experimental.private_network = true

kill_signal = "SIGINT"
kill_timeout = 5

[processes]
  db = "/surreal start -u root -p root -- file:///data"
  graph = "/product-graph"

# [env]
#   DATABASE_URL = "ederoyd-product-graph.flycast:8000"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["graph"]
  auto_stop_machines = true
  auto_start_machines = true

  [[services.ports]]
    port = 80
    handlers = ["http"]
    
  [services.concurrency]
    type = "requests"
    hard_limit = 25
    soft_limit = 20

[[services]]
  # name = "ederoyd-product-graph-db"
  protocol = "tcp"
  internal_port = 8000
  processes = ["db"]
  auto_stop_machines = true
  auto_start_machines = true
  
  [[services.ports]]
    port = 8000
    handlers = ["http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[mounts]
  source = "ederoyd_product_graph_db"
  destination = "/data"
  processes = ["db"]

