app = "ederoyd-product-graph"
app_description = "Ederoyd Product Graph"
app_version = "0.0.1"
app_license = "MIT"

kill_signal = "SIGINT"
kill_timeout = 5

[processes]
  db = "/surreal start -u root -p root"
  graph = "/product-graph"

[env]
  DATABASE_URL = "http://ederoyd-product-graph.fly.dev:8000"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["graph"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["db"]

  [[services.ports]]
    port = 8000
    handlers = ["http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
